data<-"C:/Users/hp/Desktop/household_power_consumption.txt"
Power_House<-read.table(data,sep = ";",header = TRUE,stringsAsFactors = FALSE)
head(Power_House)
Required_Data<- Power_House[Power_House$Date %in% c("1/2/2007","2/2/2007"),]
globalActivePower <- as.numeric(Required_Data$Global_active_power)
subMetering1 <- as.numeric(Required_Data$Sub_metering_1)
subMetering2 <- as.numeric(Required_Data$Sub_metering_2)
subMetering3 <- as.numeric(Required_Data$Sub_metering_3)
datetime<-strptime(paste(Required_Data$Date,Required_Data$Time),"%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(datetime, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()