data<-"C:/Users/hp/Desktop/household_power_consumption.txt"
Power_House<-read.table(data,sep = ";",header = TRUE,stringsAsFactors = FALSE)
head(Power_House)
Required_Data<- Power_House[Power_House$Date %in% c("1/2/2007","2/2/2007"),]
globalActivePower <- as.numeric(Required_Data$Global_active_power)
subMetering1 <- as.numeric(Required_Data$Sub_metering_1)
subMetering2 <- as.numeric(Required_Data$Sub_metering_2)
subMetering3 <- as.numeric(Required_Data$Sub_metering_3)
volt<-as.numeric(Required_Data$Voltage)
globalReactivePower <- as.numeric(Required_Data$Global_reactive_power)
datetime<-strptime(paste(Required_Data$Date,Required_Data$Time),"%d/%m/%Y %H:%M:%S")
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2),mar=c(4,4,2,1))
plot(datetime, globalActivePower, type="l", ylab="Global Active Power", xlab="")
plot(datetime,volt, type="l", ylab="Voltage", xlab="datetime")
plot(datetime, subMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, subMetering2, type="l", col="red")
lines(datetime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
plot(datetime,globalReactivePower, type="l", ylab="Global_Reactive_Power", xlab="datetime")
dev.off()